version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: appbank-postgres
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata: {}

