apiVersion: v1
kind: Service
metadata:
  name: ledger
  namespace: appbank
spec:
  selector:
    app: ledger
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
  namespace: appbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      containers:
        - name: ledger
          image: ghcr.io/org/ledger:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.appbank.svc.cluster.local:5432/ledger
            - name: SPRING_DATASOURCE_USERNAME
              value: ledger
            - name: SPRING_DATASOURCE_PASSWORD
              value: ledger

