apiVersion: v1
kind: Service
metadata:
  name: pix
  namespace: appbank
spec:
  selector:
    app: pix
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pix
  namespace: appbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pix
  template:
    metadata:
      labels:
        app: pix
    spec:
      containers:
        - name: pix
          image: ghcr.io/org/pix:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083

