apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: appbank
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: appbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/org/appbank-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_LEDGER_URL
              value: http://ledger.appbank.svc.cluster.local:8081
            - name: BACKEND_PAYMENTS_URL
              value: http://payments.appbank.svc.cluster.local:8082
            - name: BACKEND_PIX_URL
              value: http://pix.appbank.svc.cluster.local:8083
            - name: DEFAULT_TENANT_ID
              value: 11111111-1111-1111-1111-111111111111

