name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Gradle Cache
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean build --no-daemon
      - name: Web install
        working-directory: web
        run: npm ci
      - name: Web lint/build/test
        working-directory: web
        run: |
          npm run lint --silent || true
          npm run build --silent
          npm test --silent -- --ci --passWithNoTests
  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ledger
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/ledger/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ledger:latest
      - name: Build and push payments
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/payments/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/payments:latest
      - name: Build and push pix
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/pix/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pix:latest
      - name: Build and push web
        uses: docker/build-push-action@v6
        with:
          context: web
          file: web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/appbank-web:latest

