name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Gradle Cache
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean build --no-daemon

